pf_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',  include('pfsite.urls', namespace='pfsite')),
    path('projects/stockchecker/', include('stock.urls', namespace='stockchecker')),
    path('projects/sudoku/', include('sudoku.urls', namespace='sudoku')),
    path('projects/timezone/', include('timezone.urls', namespace='timezone')),
    path('projects/youtube/', include('youtube.urls', namespace='youtube')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pfsite/urls.py
from django.urls import path
from . import views

app_name = "pfsite"

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('projects/', views.ProjectView.as_view(), name='projects'),
    path('resume/', views.ResumeView.as_view(), name='resume')
]

stock/urls.py
from django.urls import path
# from .views import HomeView
from . import views

app_name='stock'

urlpatterns = [
	path('', views.home, name='home'),
	path('api/chart/data/', views.StockData.as_view()),
	# path('chart_view/', views.StockData.as_view())
]

timezone/urls.py
from django.urls import path
from . import views

app_name = 'timezone'

urlpatterns = [
	path('', views.home, name='timezone_home'),
]

pfsite/models.py
from django.db import models

# Create your models here.

pfsite/views.py
from django.views.generic import TemplateView

class IndexView(TemplateView):
    template_name = 'pfsite/index.html'

class ProjectView(TemplateView):
    template_name = 'pfsite/projects.html'

class ResumeView(TemplateView):
    template_name = 'pfsite/resume.html'

pfsite/templates/pfsite/index.html
{% extends 'pfsite/pfbase.html' %}

{% block content %}
<body class="index_page">
  <div class="titles">
      <h1 class="name">Penny Fang</h1>
      <p class="description">Software Engineer & Content Creator</p>
  </div>
    <div class="container">
      <table class="table-responsive">
        <table class="table table-borderless">
          <tr>
            <td id="portfolio"><a href="{% url 'pfsite:projects' %}"><button type="button" class="btn btn-dark btn-xlarge custom-button">Portfolio</button></a></td>
            <td id="resume"><a href="{% url 'pfsite:resume' %}"><button type="button" class="btn btn-dark btn-xlarge custom-button">Resume</button></a></td>
          </tr>
        </table>
        <table class="table table-borderless">
          <tr id="socialicons">
            <td>
              <a class="btn btn-social-icon btn-linkedin" id="socialmedia" href="https://www.linkedin.com/in/le-penny-fang/"><span class="fa fa-linkedin"></span></a>
              <a class="btn btn-social-icon btn-github" id="socialmedia" href="https://github.com/Pennylele"><span class="fa fa-github"></span></a>
              <a class="btn btn-social-icon btn-instagram" id="socialmedia" href="https://www.instagram.com/pennbubble/?hl=en"><span class="fa fa-instagram"></span></a>
              <a class="btn btn-social-icon btn-twitter" id="socialmedia" href="https://twitter.com/fangle0121"><span class="fa fa-twitter"></span></a>
              <a class="btn btn-social-icon btn-youtube" id="socialmedia" href="https://www.youtube.com/channel/UC6TWeFeoh_oQLxv15hswNxQ"><span class="fa fa-youtube-play"></span></a>
            </td>
          </tr>
        </table>
      </table>
    </div>
</body>
{% endblock %}

pfsite/templates/pfsite/pfbase.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Penny Fang</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'pfsite/favicon.png' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Caveat+Brush&display=swap" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'pfsite/pfsite.css' %}">
    <!-- fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Asap:wght@400;700&display=swap" rel="stylesheet">
  </head>

  <!-- drift code -->
  <!-- Start of Async Drift Code -->
  <script>
  "use strict";

  !function() {
    var t = window.driftt = window.drift = window.driftt || [];
    if (!t.init) {
      if (t.invoked) return void (window.console && console.error && console.error("Drift snippet included twice."));
      t.invoked = !0, t.methods = [ "identify", "config", "track", "reset", "debug", "show", "ping", "page", "hide", "off", "on" ],
      t.factory = function(e) {
        return function() {
          var n = Array.prototype.slice.call(arguments);
          return n.unshift(e), t.push(n), t;
        };
      }, t.methods.forEach(function(e) {
        t[e] = t.factory(e);
      }), t.load = function(t) {
        var e = 3e5, n = Math.ceil(new Date() / e) * e, o = document.createElement("script");
        o.type = "text/javascript", o.async = !0, o.crossorigin = "anonymous", o.src = "https://js.driftt.com/include/" + n + "/" + t + ".js";
        var i = document.getElementsByTagName("script")[0];
        i.parentNode.insertBefore(o, i);
      };
    }
  }();
  drift.SNIPPET_VERSION = '0.3.1';
  drift.load('vud7madzfkns');
  </script>
  <!-- End of Async Drift Code -->

  <body>
      {% block content %}
      {% endblock %}
  </body>
  <!-- Latest compiled and minified jQuery -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</html>

pfsite/templates/pfsite/projects.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col">
      </div>
      <!-- about me -->
      <div class="col-12">
        <h1 id="aboutme">About Penny Fang</h1>
        <div class="container profile_penny">
          <img src="{% static 'pfsite/profile_0.jpg' %}" alt="penny" class="img-thumbnail">
        </div>
        <div class="text-body">
          <p>Penny Fang is an aspring full stack Software Engineer and a content creator based in San Francisco, California.
            She has the industry experience as a Localization Engineer for 5 years,
            where she took the initiative to automate most manual engineering processes, which resulted
            in a deduction of 30% of the total processing time that led to larger profit margins for the organization.
            In her recent projects, she followed the lifecycle of all software products from the very initial system design to their deployment.
            The guidance provided to the team on software process and agile best practices led to a productivity increase by approximately 25%.
            Please feel free to check her <a href="{% url 'pfsite:resume' %}">resume</a>, chat with her, or email her
            at <span class="email"><a href="mailto:fangle0121@gmail.com">fangle0121@gmail.com</a></span> for any questions or potential position fit for her.</p>
        </div>
      </div>
      <!-- tech projects -->
      <div class="col-12">
        <h1 id="aboutme">Tech Projects</h1>

        <!-- Row 1 -->
        <div class="row row-cols-1 row-cols-md-3 g-4" id="project-cards">
          <div class="col">
            <div class="card">
              <img src="{% static 'pfsite/mock_interview.jpg' %}" class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title">Mock Interview Site</h5>
                <p class="card-text">This website provides users a platform to do mock tech interview practices
                  with their peers by using a live video and code editor. Users can also register
                  with the site for peer invite and see their interview session history.</p>
                <a href="https://www.themocksite.com" class="btn btn-primary">View project</a>
              </div>
            </div>
          </div>
          <div class="col">
            <div class="card">
              <img src="{% static 'pfsite/stock.jpg' %}" class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title">Stock Checker App</h5>
                <p class="card-text">This web app allows users to check a selected stock's performance over the past a few days.
                  And it calculates the best time to buy and sell the stock during this period of time, as well as the maximum profit per share.</p>
                <a href="{% url 'stock:home' %}" class="btn btn-primary">View project</a>
              </div>
            </div>
          </div>
          <div class="col">
            <div class="card">
              <img src="{% static 'pfsite/sudoku.jpg' %}" class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title">Sudoku Game On</h5>
                <p class="card-text">This app gives users the ultimate flexibility to create their own games.
                  If the input is not valid, an error would show on the click of the solve button.
                  Otherwise, the solve button would solve/complete the puzzle.</p>
                <a href="{% url 'sudoku:home' %}" class="btn btn-primary">View project</a>
              </div>
            </div>
          </div>
        </div>

      <!-- Row 2 -->
        <div class="row row-cols-1 row-cols-md-3 g-4">
          <div class="col">
            <div class="card">
              <img src="{% static 'pfsite/almond-n-chai.jpg' %}" class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title">Almond and Chai Blog</h5>
                <p class="card-text">This blog app takes full advantage of Django's powerful user management system.
                  Users can register, reset their password, as well as log in and out. They can create, update, and delete
                  their own posts and profiles. They can also comment on others' posts and filter posts by a particular author.</p>
                <a href="https://almond-n-chai.herokuapp.com/" class="btn btn-primary">View project</a>
              </div>
            </div>
          </div>
          <div class="col">
            <div class="card">
              <img src="{% static 'pfsite/vlog.jpg' %}" class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title">Penny Fang Vlog</h5>
                <p class="card-text">This app talks with YouTube API to update the views of the existing videos.
                I did this as a practice to fetch and manipulate data from my own youtube channel. It allows users to search, filter, and sort videos
                based on keywords and publication date, as well as watch those videos from this website.</p>
                <a href="{% url 'youtube:home' %}" class="btn btn-primary">View project</a>
              </div>
            </div>
          </div>
          <div class="col">
            <div class="card">
              <img src="{% static 'pfsite/timezone.jpg' %}" class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title">Timezone Pocket Daemon</h5>
                <p class="card-text">This app is inspired by my previous work when my team members are all over the world.
                It'd be very handy when one wants to convert his/her current date and time into a desired time zone.
                This app is very lightweight and displays the user's time zone information by default.</p><br>
                <a href="{% url 'timezone:timezone_home' %}" class="btn btn-primary">View project</a>
              </div>
            </div>
          </div>
        </div>
      <div class="col-md-2 col-lg-3">
      </div>
    </div>
  </div>
{% endblock %}

pfsite/templates/pfsite/resume.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <!-- work history -->
    <h1 id="sectiontitle">Work History</h1>
    <!-- card 1 -->
    <div class="card mb-3" id="resumecard" style="max-width: 800px;">
      <div class="row g-0">
        <div class="col-md-4">
          <img src="{% static 'pfsite/venga.jpg' %}" alt="localization engineer">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">Localization Engineer</h5>
            <p class="card-text"><small class="text-muted">@Venga Global | 4 years 11 months</small></p>
            <ul class="card-text" style="text-align: left">
              <li>Led and centralized complex and high-profile engineering process for projects of critical accounts. </li>
              <li>Initiated the automation solutions for various software localizaiton projects, which drove down manual processing time 25 times, and increased the profit margin by approximately 30%.</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <!-- card 2 -->
    <div class="card mb-3" id="resumecard" style="max-width: 800px;">
      <div class="row g-0">
        <div class="col-md-4">
          <img src="{% static 'pfsite/unitar.jpg' %}" alt="unitar">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">Project Manager</h5>
            <p class="card-text"><small class="text-muted">@United Nations Institute for Training & Research - UNITAR | 2 months</small></p>
            <ul class="card-text" style="text-align: left">
              <li>Planned and organized the project life cycle – scope, cost, timeline, and risks.</li>
              <li>Built and cultivated the entire team from scratch.</li>
              <li>Assured the project quality and expediated its delivery deadline by 1 week.</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <!-- card 3 -->
    <div class="card mb-3" id="resumecard" style="max-width: 800px;">
      <div class="row g-0">
        <div class="col-md-4">
          <img src="{% static 'pfsite/teacher.jpg' %}" alt="Chinese teacher">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">Lead Chinese Teacher</h5>
            <p class="card-text"><small class="text-muted">@Michigan State University | 9 months</small></p>
            <ul class="card-text" style="text-align: left;"><li>Classroom teaching and management. Student evaluation. People management.</li></ul>
          </div>
        </div>
      </div>
    </div><br>

    <!-- Education -->
  <div class="container">
    <h1 id="sectiontitle">Education</h1>
    <div class="card-group">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Master's of Computer Science</h5>
        <p class="card-text"></p>
        <p class="card-text"><small class="text-muted">@International Technological University | 2019 - 2020</small></p>
      </div>
    </div>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Master's of Translation and Localization Management</h5>
        <p class="card-text"></p>
        <p class="card-text"><small class="text-muted">@Middlebury Institute of International Studies at Monterey | 2013 - 2015</small></p>
      </div>
    </div>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Master's of Teaching English to Speakers of Other Languages</h5>
        <p class="card-text"></p>
        <p class="card-text"><small class="text-muted">@Michigan State University | 2011 - 2013</small></p>
      </div>
    </div>
  </div><br>
    <!-- courses taken -->
    <h1 id="sectiontitle">Courses Taken</h1>
    <div class="card text-center">
      <div class="card-header">
        Featured
      </div>
      <div class="card-body">
        <h5 class="card-title">M.S. Computer Science</h5>
        <p class="card-text">Computer Algorithm | Advanced Computer Algorithm | Software Engineering | OS & Distributed Systems | Cloud Computing | OOP with C++</p>
      </div>
      <div class="card-footer text-muted">
        GPA: 3.92
      </div>
    </div><br>
    <!-- certificate -->
    <h1 id="sectiontitle">Certificate</h1>
    <div class="row">
      <div class="col-sm-6">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Python and Django Full Stack Web Developer Bootcamp</h5>
            <p class="card-text"></p>
            <a href="http://ude.my/UC-837bc473-acdc-434c-ba3f-b1c74478837" class="btn btn-primary">Certificate</a>
          </div>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Software Processes and Agile Practices</h5>
            <p class="card-text"></p>
            <a href="https://www.coursera.org/account/accomplishments/verify/6ARUXR3BE5SK" class="btn btn-primary">Certificate</a>
          </div>
        </div>
      </div>
    </div>
</div>
{% endblock %}