pf_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',  include('pfsite.urls', namespace='pfsite')),
    path('projects/stockchecker/', include('stock.urls', namespace='stockchecker')),
    path('projects/sudoku/', include('sudoku.urls', namespace='sudoku')),
    path('projects/timezone/', include('timezone.urls', namespace='timezone')),
    path('projects/youtube/', include('youtube.urls', namespace='youtube')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pfsite/urls.py
from django.urls import path
from . import views

app_name = "pfsite"

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('projects/', views.ProjectView.as_view(), name='projects'),
    path('resume/', views.ResumeView.as_view(), name='resume')
]

stock/urls.py
from django.urls import path
# from .views import HomeView
from . import views

app_name='stock'

urlpatterns = [
	path('', views.home, name='home'),
	path('api/chart/data/', views.StockData.as_view()),
	# path('chart_view/', views.StockData.as_view())
]

youtube/urls.py
from .views import VideoListView, SearchResultsView, FilterByViews, VideoDetailView, Sync
from django.urls import path

app_name='youtube'

urlpatterns = [
    path('', VideoListView.as_view(), name='home'),
    path('search/', SearchResultsView.as_view(), name='search_results'),
    path('sort-by-views/', FilterByViews.as_view(), name='sort_views'),
    path('video-detail/<slug>/', VideoDetailView.as_view(), name='video_detail'),
    path('sync/', Sync, name='sync'),
]

youtube/models.py
from django.db import models
from django.utils.text import slugify
from embed_video.fields import EmbedVideoField
from django.utils import timezone
from PIL import Image

# Create your models here.
from embed_video.fields import EmbedVideoField

class Video(models.Model):
	video = EmbedVideoField()
	title = models.CharField(max_length=150, default="Video")
	video_id = models.CharField(max_length=150, default="000000000000000")
	date_posted = models.CharField(max_length=20, default="0000-00-00")
	thumbnail = models.CharField(max_length=50, default="https://i.ytimg.com/vi/7NpvXBM4-1A/mqdefault.jpg")
	description = models.TextField(default="Enjoy!")
	views = models.IntegerField(default=0)
	slug = models.SlugField(max_length=150, default="none", allow_unicode=True)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("video_detail", kwargs={"slug": self.slug})

youtube/forms.py
from django import forms


class SyncForm(forms.Form):
	r = forms.CharField(label="Sync")

youtube/views.py
from django.shortcuts import render
from .models import Video
from django.views.generic import ListView, DetailView
from .forms import SyncForm
from django.db.models import Q
from googleapiclient.discovery import build
import os

api_key = os.environ.get('yt_api_key')
youtube = build('youtube', 'v3', developerKey=api_key)
playlist_id = 'UU6TWeFeoh_oQLxv15hswNxQ'

# Create your views here.
def home(request):
	context = {
		'videos': Video.objects.all().order_by('-date_posted'),
	}

	return render(request, 'youtube/home.html', context)

class VideoListView(ListView):
	model = Video
	template_name = 'youtube/home.html'
	context_object_name = 'videos'

	paginate_by = 9
	ordering = ['-date_posted']

class SearchResultsView(ListView):
	model = Video
	template_name = 'youtube/search_results.html'

	def get_queryset(self):
		query = self.request.GET.get('q')
		video_list = Video.objects.filter(
			Q(title__icontains=query)
		)
		return video_list

class FilterByViews(ListView):
	model = Video
	template_name = 'youtube/sort_views.html'
	context_object_name = 'videos'

	ordering = ['-views']
	paginate_by = 9

class VideoDetailView(DetailView):
	model = Video

def Sync(request):
	cxt = {}
	#Getting all the views and urls of the current videos in the playlist
	if request.method=="POST":
		videos = []

		nextPageToken = None
		while True:
			pl_request = youtube.playlistItems().list(
				part='contentDetails, snippet',
				playlistId=playlist_id,
				maxResults=80,
				pageToken=nextPageToken
			)

			pl_response = pl_request.execute()

			vid_ids = {}
			for item in pl_response['items']:
				videoId = item['contentDetails']['videoId']
				vid_ids[videoId] = {'title': item['snippet']['title'],'description': item['snippet']['description'], 'date_posted': item['snippet']['publishedAt'], 'thumbnail': item['snippet']['thumbnails']['medium']['url']}


			vid_request = youtube.videos().list(
				part="statistics",
				id=','.join(vid_ids)
			)

			vid_response = vid_request.execute()


			for item in vid_response['items']:
				vid_views = item['statistics']['viewCount']

				vid_id = item['id']
				yt_link = f'https://www.youtube.com/watch?v={vid_id}'
				description = vid_ids[vid_id]['description']
				title = vid_ids[vid_id]['title']
				date_posted = vid_ids[vid_id]['date_posted']
				thumbnail = vid_ids[vid_id]['thumbnail']

				videos.append(
					{
						'views': int(vid_views),
						'url': yt_link,
						'description': description,
						'title': title,
						'date_posted': date_posted,
						'thumbnail': thumbnail,
						'slug': vid_id
					}
				)

			nextPageToken = pl_response.get('nextPageToken')

			if not nextPageToken:
				break

		videos.sort(key=lambda vid: vid['views'], reverse=True)

		vids = []
		vidId = []
		nextPageToken = None
		
		# Updating the current views
		for video in videos:
			try:
				# Video.objects.get(video=video['url'])
				r = Video.objects.get(video=video['url'])

				r.views = video['views']
				# r.thumbnail = video['thumbnail']
				# r.slug = video['slug']
				r.save()
			except Video.DoesNotExist:
				# Creating the new video
				v = Video(video=video['url'], title=video['title'], date_posted=video['date_posted'], description=video['description'], views=video['views'], thumbnail=video['thumbnail'], slug=video['slug'])
				v.save() 
		
		cxt['args'] = videos

		# return render(request, 'youtube/sync.html', cxt)
	return render(request, 'youtube/sync.html', cxt)

youtube/templates/youtube/base.html
{% load embed_video_tags %}
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- main.css --> 
    <link rel="stylesheet" type="text/css" href="{% static 'youtube/css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'pfsite/master.css' %}">


    <!-- fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap" rel="stylesheet">

    <title>Penny Fang</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'pfsite/favicon.png' %}">
  </head>

  <!-- drift code -->
  <script>
    "use strict";

    !function() {
      var t = window.driftt = window.drift = window.driftt || [];
      if (!t.init) {
        if (t.invoked) return void (window.console && console.error && console.error("Drift snippet included twice."));
        t.invoked = !0, t.methods = [ "identify", "config", "track", "reset", "debug", "show", "ping", "page", "hide", "off", "on" ],
        t.factory = function(e) {
          return function() {
            var n = Array.prototype.slice.call(arguments);
            return n.unshift(e), t.push(n), t;
          };
        }, t.methods.forEach(function(e) {
          t[e] = t.factory(e);
        }), t.load = function(t) {
          var e = 3e5, n = Math.ceil(new Date() / e) * e, o = document.createElement("script");
          o.type = "text/javascript", o.async = !0, o.crossorigin = "anonymous", o.src = "https://js.driftt.com/include/" + n + "/" + t + ".js";
          var i = document.getElementsByTagName("script")[0];
          i.parentNode.insertBefore(o, i);
        };
      }
    }();
    drift.SNIPPET_VERSION = '0.3.1';
    drift.load('vud7madzfkns');
    </script>

  <body>
     <!-- header section -->
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'pfsite:index' %}"><strong>Penny Fang</strong></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'pfsite:index' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'pfsite:projects' %}">Portfolio</a>
              <a class="nav-item nav-link" href="{% url 'pfsite:resume' %}">Resume</a>
            </div>
            <div class="topnav-right">
              <a class="btn btn-social-icon btn-linkedin" id="socialmedia" href="https://www.linkedin.com/in/le-penny-fang/"><span class="fa fa-linkedin"></span></a>
              <a class="btn btn-social-icon btn-github" id="socialmedia" href="https://github.com/Pennylele"><span class="fa fa-github"></span></a>
              <a class="btn btn-social-icon btn-instagram" id="socialmedia" href="https://www.instagram.com/pennbubble/?hl=en"><span class="fa fa-instagram"></span></a>
              <a class="btn btn-social-icon btn-twitter" id="socialmedia" href="https://twitter.com/fangle0121"><span class="fa fa-twitter"></span></a>
              <a class="btn btn-social-icon btn-youtube" id="socialmedia" href="https://www.youtube.com/channel/UC6TWeFeoh_oQLxv15hswNxQ"><span class="fa fa-youtube-play"></span></a>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <!-- header section -->
    <main class="flex-shrink-0">
        <a href="{% url 'youtube:home' %}"><h1 class="header">Penny Fang VLOG
        <div class="g-ytsubscribe" data-channelid="UC6TWeFeoh_oQLxv15hswNxQ" data-layout="default" data-count="default"></div></h1></a>
        <div class="container">
          {% block content %}{% endblock %}
        </div>
        <div class="container">
            {% if is_paginated %}
                {% if page_obj.has_previous %}
                  <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
                  <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}
                  {% if page_obj.number == num %}
                    <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
                  {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                    <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
                  {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                  <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
                  <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                {% endif %}
            {% endif %}
        </div>
    </main>
    <!-- footer -->
    <footer class="footer mt-auto py-3 bg-light">
      <div class="container">
        <span class="text-muted">This website is built on Django &copy; Penny Fang.</span>
      </div>
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <!-- subscribe YT--> 
    <script src="https://apis.google.com/js/platform.js"></script>
  </body>
</html>

youtube/templates/youtube/home.html
{% extends 'youtube/base.html' %}
{% load static %}
{% block content %}
<div class="input-group mb-3">
	<form action="{% url 'youtube:search_results' %}" method="GET">
		<input type="text" name="q" class="form-control" placeholder="Search..." aria-label="Recipient's username" aria-describedby="button-addon2">
	</form>
	<div class="dropdown" style="margin-left: 2em;">
	  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		Sort by
	  </button>
	  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
		<a class="dropdown-item" href="{% url 'youtube:home' %}">Date</a>
		<a class="dropdown-item" href="{% url 'youtube:sort_views' %}">Views</a>
	  </div>
	</div>
</div>

	{% for video in videos %}
		<figure class="figure">
			<img src="{{ video.thumbnail }}" class="figure-img img-fluid rounded">
			<figcaption class="figure-caption" id="cp-title"><a href="{% url 'youtube:video_detail' slug=video.slug %}"><strong>{{ video.title|wordwrap:30|linebreaksbr|truncatechars:50 }}</strong></a></figcaption>
			<figcaption class="figure-caption">{{ video.date_posted|slice:10}}   {{ video.views }} views</figcaption>
		</figure>
	{% endfor %}
{% endblock %}

youtube/templates/youtube/search_results.html
{% extends 'youtube/base.html' %}
{% load static %}
{% block content %}
	<p>Search results</p>
	{% for video in video_list %}
		<figure class="figure">
			<img src="{{ video.thumbnail }}" class="figure-img img-fluid rounded">
			<figcaption class="figure-caption" id="cp-title"><a href="{% url 'youtube:video_detail' slug=video.slug %}"><strong>{{ video.title|wordwrap:30|linebreaksbr|truncatechars:50 }}</strong></a></figcaption>
			<figcaption class="figure-caption">{{ video.date_posted|slice:10}}   {{ video.views }} views</figcaption>
		</figure>
	{% endfor %}
{% endblock %}

youtube/templates/youtube/sort_views.html
{% extends 'youtube/base.html' %}
{% load static %}
{% block content %}
	<div class="input-group mb-3">
		<form action="{% url 'youtube:search_results' %}" method="GET">
		  	<input type="text" name="q" class="form-control" placeholder="Search..." aria-label="Recipient's username" aria-describedby="button-addon2">
		</form>
		<div class="dropdown" style="margin-left: 2em;">
		  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		    Sort by
		  </button>
		  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
		    <a class="dropdown-item" href="{% url 'youtube:home' %}">Date</a>
		    <a class="dropdown-item" href="{% url 'youtube:sort_views' %}">Views</a>
		  </div>
		</div>
	</div>
	<p>Sorted by views</p>
	{% for video in videos %}
		<figure class="figure">
			<img src="{{ video.thumbnail }}" class="figure-img img-fluid rounded">
			<figcaption class="figure-caption" id="cp-title"><a href="{% url 'youtube:video_detail' slug=video.slug %}"><strong>{{ video.title|wordwrap:30|linebreaksbr|truncatechars:50 }}</strong></a></figcaption>
			<figcaption class="figure-caption">{{ video.date_posted|slice:10}}   {{ video.views }} views</figcaption>
		</figure>
	{% endfor %}
{% endblock %}

youtube/templates/youtube/sync.html
{% extends 'youtube/base.html' %}
{% load static %}
{% block content %}
	<form method="POST">
		{% csrf_token %} 
		<button class="btn btn-dark" type="submit" name="button">Sync</button>
	</form>
	<div class="container">
	  <p>{{ args }}</p>
	  <p>{{ args2 }}</p>
	</div>
{% endblock %}

youtube/templates/youtube/video_detail.html
{% extends 'youtube/base.html' %}
{% load static %}
{% load embed_video_tags %}
{% block content %}
	<div class="jumbotron">
	  {% video video.video "960x540" %}
	  <p class="lead"><strong>{{ video.title }}</strong></p>
	  <hr class="my-4">
  	  <p>{{ video.description|linebreaks }}</p>
	</div>
{% endblock %}